//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeznekDB : DbContext
    {
        public HeznekDB()
            : base("name=HeznekDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academicInstitutTbl> academicInstitutTbl { get; set; }
        public virtual DbSet<bank> bank { get; set; }
        public virtual DbSet<cityTbl> cityTbl { get; set; }
        public virtual DbSet<contactStudentCandidate> contactStudentCandidate { get; set; }
        public virtual DbSet<eventTbl> eventTbl { get; set; }
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<loginAndPermissions> loginAndPermissions { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<scholarship> scholarship { get; set; }
        public virtual DbSet<serviceTbl> serviceTbl { get; set; }
        public virtual DbSet<statusTbl> statusTbl { get; set; }
        public virtual DbSet<studentScholarship> studentScholarship { get; set; }
        public virtual DbSet<studyFieldTbl> studyFieldTbl { get; set; }
        public virtual DbSet<userTbl> userTbl { get; set; }
        public virtual DbSet<userTypeTbl> userTypeTbl { get; set; }
    }
}
