//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeznekLaatid.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTbl()
        {
            this.contactStudentCandidate = new HashSet<contactStudentCandidate>();
            this.contactStudentCandidate1 = new HashSet<contactStudentCandidate>();
            this.files = new HashSet<files>();
            this.messages = new HashSet<messages>();
            this.messages1 = new HashSet<messages>();
            this.studentScholarship = new HashSet<studentScholarship>();
            this.eventTbl = new HashSet<eventTbl>();
        }
    
        public string id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public int status { get; set; }
        public Nullable<int> yearsInTheProgram { get; set; }
        public string requestStatus { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> cityNumber { get; set; }
        public string address { get; set; }
        public Nullable<int> numOfSiblings { get; set; }
        public Nullable<int> academicParents { get; set; }
        public string school { get; set; }
        public Nullable<int> yearFinishSchool { get; set; }
        public int typeOfService { get; set; }
        public Nullable<int> academicInstitution { get; set; }
        public Nullable<int> studyField { get; set; }
        public Nullable<int> startYear { get; set; }
        public Nullable<int> excpectedCompletionYear { get; set; }
        public string learningDisabilities { get; set; }
        public Nullable<int> psychometricGrade { get; set; }
        public string anotherScholarship { get; set; }
        public string educationFunding { get; set; }
        public string difficulties { get; set; }
        public Nullable<int> bankName { get; set; }
        public Nullable<int> numOfBank { get; set; }
        public Nullable<int> numAccount { get; set; }
        public Nullable<int> avergeDegree { get; set; }
        public Nullable<int> typeOfDegree { get; set; }
        public string comments { get; set; }
    
        public virtual academicInstitutTbl academicInstitutTbl { get; set; }
        public virtual bank bank { get; set; }
        public virtual cityTbl cityTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactStudentCandidate> contactStudentCandidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactStudentCandidate> contactStudentCandidate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<files> files { get; set; }
        public virtual loginAndPermissions loginAndPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messages> messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<messages> messages1 { get; set; }
        public virtual serviceTbl serviceTbl { get; set; }
        public virtual statusTbl statusTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentScholarship> studentScholarship { get; set; }
        public virtual studyFieldTbl studyFieldTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventTbl> eventTbl { get; set; }
    }
}
